# CONTAINER MICRO-FE CONFIG FILE
name: deploy-container
on:
  push:
    branches:
      - develop
    paths:
      - './**'
defaults:
  run:
    working-directory: ./
jobs:
  build:
    # VM to use
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm build

      # AWS deployment
      - uses: cipollafrancesco/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
